
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account-service-deployment
  name: account-service-deployment
spec:
  ports:
    - port: 8082
      name: metrics-port
      protocol: TCP
      targetPort: 8080
#      nodePort: 30003
  selector:
    app: account-service-deployment
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels: 
    app: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-deployment
  template:
    metadata:
      labels:
        app: account-service-deployment
    spec:
      containers:
      - name: account-service
        image: nileshgule/account-service
        imagePullPolicy: Always
        ports:
#          - name: port-acct-svc
          - name: metrics-port
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 45
          periodSeconds: 5
          failureThreshold: 5
        env:
          - name: "JAVA_OPTS"
            value: "-javaagent:/app/opentelemetry-javaagent.jar"
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -jar /app/app.jar --spring.profiles.active=k8s