
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: forex-service-deployment
  name: forex-service-deployment
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
#      nodePort: 30004
  selector:
    app: forex-service-deployment
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-service-deployment
  labels: 
    app: forex-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-service-deployment
  template:
    metadata:
      labels:
        app: forex-service-deployment
    spec:
      containers:
      - name: forex-service
        image: nileshgule/forex-service
        imagePullPolicy: Always
        ports:
          - name: port-fx-svc
            containerPort: 8083
        env:
          - name: "JAVA_OPTS"
            value: "-javaagent:/app/opentelemetry-javaagent.jar"
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -jar /app/app.jar --spring.profiles.active=k8s