server:
  port: 8084
  servlet:
    context-path: /transaction-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

spring:
  application:
    name: transaction-service
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317

tracing:
  url: http://localhost:4318/v1/traces

  management:
    tracing:
      sampling:
        probability: 1.0