server:
  servlet:
    context-path: /backend-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

spring:
  security:
    basic:
      enabled: false
  application:
    name: backend-service
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317

tracing:
  url: http://localhost:4318/v1/traces

  management:
    tracing:
      sampling:
        probability: 1.0

#  ssl:
#    enabled: ${tomcat_ssl_enabled:false}
#    key-store: ${tomcat_key_store_path}
#    key-store-password: ${tomcat_key_store_pwd}
#    key-store-type: ${tomcat_key_store_type}
#    key-alias: ${tomcat_key_store_alias}

authenticate_service_url: http://localhost:8081/authentication-service/authenticate/token?token={token}
account_by_customer_url: http://localhost:8082/account-service/{customerId}
account_by_customer_currency_url: http://localhost:8082/account-service/{customerId}/{currency}
forex_url: http://localhost:8083/forex-service/rates
transaction_service_url: http://localhost:8084/transaction-service//accountTransactions

services:
  url:
    authenticate-service: ${authenticate_service_url}
    customer-account-service-customer: ${account_by_customer_url}
    customer-account-service-customer-currency: ${account_by_customer_currency_url}
    exchange-rate: ${forex_url}
    account-transaction-service: ${transaction_service_url}
#
#
#
#logging:
#  file:
#    name: application.log
#    path: /logs/
#  level:
#    root: info
#    org.springframework: error
#    org.hibernate: error
#    com.mycompany.api: info