services:
  endpoint:
    authenticate: http://${AUTHENTICATION_SERVICE_DEPLOYMENT_SERVICE_HOST}:${AUTHENTICATION_SERVICE_DEPLOYMENT_SERVICE_PORT}
    account: http://${ACCOUNT_SERVICE_DEPLOYMENT_SERVICE_HOST}:${ACCOUNT_SERVICE_DEPLOYMENT_SERVICE_PORT}
    forex: http://${FOREX_SERVICE_DEPLOYMENT_SERVICE_HOST}:${FOREX_SERVICE_DEPLOYMENT_SERVICE_PORT}
    transaction: http://${TRANSACTION_SERVICE_DEPLOYMENT_SERVICE_HOST}:${TRANSACTION_SERVICE_DEPLOYMENT_SERVICE_PORT}