spring:
  application:
    name: backend-service

server:
#  port: 8087
  servlet:
    context-path: /backend-service

services:
  endpoint:
    authenticate: http://localhost:8081
    account: http://localhost:8082
    forex: http://localhost:8083
    transaction: http://localhost:8084
  url:
    authenticate-service: ${services.endpoint.authenticate}/authentication-service/authenticate/token?token={token}
    account-service-customer: ${services.endpoint.account}/account-service/{customerId}
    account-service-customer-currency: ${services.endpoint.account}/account-service/{customerId}/{currency}
    exchange-rate: ${services.endpoint.forex}/forex-service/rates
    account-transaction-service: ${services.endpoint.transaction}/transaction-service//accountTransactions

#  ssl:
#    enabled: ${tomcat_ssl_enabled:false}
#    key-store: ${tomcat_key_store_path}
#    key-store-password: ${tomcat_key_store_pwd}
#    key-store-type: ${tomcat_key_store_type}
#    key-alias: ${tomcat_key_store_alias}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#logging:
#  file:
#    name: application.log
#    path: /logs/
#  level:
#    root: info
#    org.springframework: error
#    org.hibernate: error
#    com.mycompany.api: info