services:
  endpoint:
    authenticate: http://authentication-service:8081
    account: http://account-service:8082
    forex: http://forex-service:8083
    transaction: http://transaction-service:8084