
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account-service-deployment
  name: account-service-deployment
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30003
  selector:
    app: account-service-deployment
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels: 
    app: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-deployment
  template:
    metadata:
      labels:
        app: account-service-deployment
    spec:
      containers:
      - name: account-service
        image: docker.io/library/account-service
        imagePullPolicy: Never
        ports:
          - name: port-acct-svc
            containerPort: 8082
        env:
          - name: "JAVA_OPTS"
            value: "-javaagent:/app/opentelemetry-javaagent.jar"
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -jar /app/app.jar --spring.profiles.active=k8s