
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: forex-service-deployment
  name: forex-service-deployment
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30004
  selector:
    app: forex-service-deployment
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-service-deployment
  labels: 
    app: forex-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-service-deployment
  template:
    metadata:
      labels:
        app: forex-service-deployment
    spec:
      containers:
      - name: forex-service
        image: docker.io/library/forex-service
        imagePullPolicy: Never
        ports:
          - name: port-fx-svc
            containerPort: 8083
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -javaagent:/app/opentelemetry-javaagent.jar  -jar /app/app.jar --spring.profiles.active=k8s