apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels: 
    app: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-deployment
  template:
    metadata:
      labels:
        app: jaeger-deployment
    spec:
      containers:
      - name: jaeger-service
        image: jaegertracing/all-in-one:latest
        ports:
          - name: jaeger-port
            containerPort: 14250
          - name: jaeger-ui-port
            containerPort: 16686
        env:
          - name: "COLLECTOR_OTLP_ENABLED"
            value: "true"
