receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true

  otlp:
    endpoint: "jaeger-service:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, jaeger ] # [otlp, logging, spanmetrics]
    metrics:
      receivers: [ otlp ] # spanmetrics
      exporters: [ logging ] # [prometheus, logging]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]