
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transaction-service-deployment
  name: transaction-service-deployment
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
      nodePort: 30005
  selector:
    app: transaction-service-deployment
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  labels: 
    app: transaction-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service-deployment
  template:
    metadata:
      labels:
        app: transaction-service-deployment
    spec:
      containers:
      - name: transaction-service
        image: docker.io/library/transaction-service
        imagePullPolicy: Never
        ports:
          - name: port-txn-svc
            containerPort: 8084
        env:
          - name: "JAVA_OPTS"
            value: "-javaagent:/app/opentelemetry-javaagent.jar"
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -jar /app/app.jar --spring.profiles.active=k8s
