
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transaction-service-deployment
    monitoring: service-monitoring-prometheus
  name: transaction-service-deployment
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
#      nodePort: 30005
  selector:
    app: transaction-service-deployment
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  labels: 
    app: transaction-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service-deployment
  template:
    metadata:
      labels:
        app: transaction-service-deployment
    spec:
      containers:
      - name: transaction-service
        image: docker.io/library/transaction-service
        imagePullPolicy: Never
        ports:
          - name: app-port
            containerPort: 8084
        command:
          - /bin/bash
          - -c
          - java --add-opens java.base/java.lang=ALL-UNNAMED -javaagent:/app/opentelemetry-javaagent.jar  -jar /app/app.jar --spring.profiles.active=k8s
        livenessProbe:
          httpGet:
            port: 8084
            path: /transaction-service/actuator/health/liveness
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8084
            path: /transaction-service/actuator/health/readiness
          initialDelaySeconds: 45
          periodSeconds: 5
          failureThreshold: 5
