
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transaction-service-deployment
    monitoring: service-monitoring-prometheus
  name: transaction-service-deployment
spec:
  ports:
    - port: 8084
      name: metrics-port
      protocol: TCP
      targetPort: 8084
  selector:
    app: transaction-service-deployment
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  labels: 
    app: transaction-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service-deployment
  template:
    metadata:
      labels:
        app: transaction-service-deployment
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: transaction-service
#        image: docker.io/library/transaction-service
#        imagePullPolicy: Never
        image: nileshgule/transaction-service
        imagePullPolicy: Always
        ports:
          - name: app-port
            containerPort: 8084
        env:
          - name: "OTEL_SERVICE_NAME"
            value: "transaction-service"
          - name: "OTEL_METRICS_EXPORTER"
            value: "prometheus"
          - name: "OTEL_TRACES_EXPORTER"
            value: "jaeger"
          - name: "OTEL_EXPORTER_JAEGER_ENDPOINT"
            value: "http://simplest-collector:14250"
        command:
          - /bin/bash
          - -c
          - java -jar /app/app.jar
        livenessProbe:
          httpGet:
            port: 8084
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            port: 8084
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 5