spring:
  application:
    name: authentication-service

server:
  port: 8081
#  servlet:
#    context-path: /authentication-service

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0