---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finance-demo-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: account-service-deployment
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics-port
      path: "/actuator/prometheus"