server:
  port: 8082
  servlet:
    context-path: /account-service

spring:
  application:
    name: account-service
#  sleuth:
#    otel:
#      config:
#        trace-id-ratio-based: 1.0
#      exporter:
#        otlp:
#          endpoint: http://localhost:4317

tracing:
  url: http://localhost:4318/v1/traces

  management:
    tracing:
      sampling:
        probability: 1.0

    endpoints:
      web:
        exposure:
          include: info,health,metrics,loggers,beans,mappings,prometheus
    metrics:
      tags:
        application: ${spring.application.name}
      export:
        prometheus:
          enabled: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true


# Prometheus metrics
#  management.endpoint.metrics.enabled=true
#  management.endpoint.prometheus.enabled=true
#  management.metrics.export.prometheus.enabled=true
