server:
  port: 8082
  servlet:
    context-path: /account-service

spring:
  application:
    name: account-service

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
#  tracing:
#    sampling:
#      probability: 1.0