springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

spring:
  security:
    basic:
      enabled: false
  application:
    name: backend-app
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  tracing:
    url: http://localhost:4318/v1/traces

  management:
    tracing:
      sampling:
        probability: 1.0


server:
  servlet:
    context-path: /backend
#  ssl:
#    enabled: ${tomcat_ssl_enabled:false}
#    key-store: ${tomcat_key_store_path}
#    key-store-password: ${tomcat_key_store_pwd}
#    key-store-type: ${tomcat_key_store_type}
#    key-alias: ${tomcat_key_store_alias}

services:
  url:
    exchange-rate: ${exchange_rate_url}
    customer-account-service-customer: ${customer_account_service_customer_url}
    customer-account-service-customer-currency: ${customer_account_service_customer_currency_url}
    account-transaction-service: ${account_transaction_service_url}
    authenticate-service: ${authenticate_service_url}

logging:
  file:
    name: application.log
    path: /logs/
  level:
    root: info
    org.springframework: warn
    org.hibernate: error
    com.mycompany.api: info