apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      # Data sources: traces
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
  
      otlp:
        protocols:
          grpc:
          http:
  
    processors:
      batch:
  
    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: jaeger-service-deployment:14250
        tls:
          insecure: true
      otlp:
        endpoint: "otel-collector-service-deployment:4317"
        tls:
          insecure: true
  
  
    service:
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [ batch ]
          exporters:  [ logging, jaeger ] # [otlp, logging, spanmetrics]
        metrics:
          receivers: [ otlp ] # spanmetrics
          processors: [ batch ]
          exporters: [ logging, otlp ] # [prometheus, logging]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging, otlp ]