otel-config:
  yml:
receivers:
  # Data sources: traces
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
      http:
#        cors:
#          allowed_origins:
#            - "http://*"
#            - "https://*"

################# Wildcard Option 1 ################
#          allowed_origins: [ "*" ]

################# Individual services ################
#          - https://localhost:8080
#          - https://localhost:3000
#          - http://localhost:3000
##          allowed_headers: [ "*" ]

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true
  otlp:
    endpoint: "otel-collector:4317"
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, jaeger ] # [otlp, logging, spanmetrics]
#    metrics:
#      receivers: [ otlp ] # spanmetrics
#      processors: [ batch ]
#      exporters: [ logging, otlp ] # [prometheus, logging]
#    logs:
#      receivers: [ otlp ]
#      processors: [ batch ]
#      exporters: [ logging, otlp ]