apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service-deployment
  labels:
    app: opentelemetry
    component: otel-collector-service-deployment
spec:
  ports:
    - name: otlp1 # Default endpoint for otlp receiver.
      port: 4317
      #      protocol: TCP
      targetPort: 4317
    - name: otlp2 # Default endpoint for otlp receiver.
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics # Default endpoint for metrics.
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    component: otel-collector-service-deployment
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-service-deployment
  labels:
    app: opentelemetry
    component: otel-collector-service-deployment
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector-service-deployment
    spec:
      containers:
        - image: otel/opentelemetry-collector:0.72.0
          imagePullPolicy: Never
          name: otel-collector-service-deployment
          ports:
            - containerPort: 4317 # Default GRPC endpoint for otlp receiver.
            - containerPort: 4318 # Default TCP endpoint for otlp receiver.
            - containerPort: 8888 # Default endpoint for querying metrics.
            - containerPort: 8889 # Default endpoint for querying metrics.
          command:
            - "/otelcol"
            - "--config=/conf/otel-agent-config.yaml"
          volumeMounts:
            - name: otel-agent-conf-vol
              mountPath: /conf
      volumes:
        - name: otel-agent-conf-vol
          configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml

